/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\StageAllStatic_v001ALPHA.glb 
*/

// gltfjsx -t has errors on converting to tsx? look into so im not forced to use jsx for all my models

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Stage(props) {
  const { nodes, materials } = useGLTF('/models/alpha_ver/StageAllStatic_v001ALPHA.glbb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} />
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[-5.482, 2.994, 1.5]} rotation={[Math.PI / 2, 0, 0]} scale={[2.701, 1, 3.061]} />
      <mesh geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} position={[5.581, 2.994, 1.5]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[2.701, 1, 3.061]} />
      <mesh geometry={nodes.Plane002.geometry} material={nodes.Plane002.material} position={[5.081, 2.994, -1.5]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[3.241, 1, 3.061]} />
      <mesh geometry={nodes.Plane003.geometry} material={nodes.Plane003.material} position={[-4.982, 2.994, -1.5]} rotation={[Math.PI / 2, 0, 0]} scale={[3.241, 1, 3.061]} />
    </group>
  )
}

useGLTF.preload('/models/alpha_ver/StageAllStatic_v001ALPHA.glb')
